### ISSUE TITLE
about @ in this line

### ISSUE THREAD

**Issue by HuXiLiFeng** [AIgen/df-posthoc-calibration#2]
https://github.com/AIgen/df-posthoc-calibration/blob/109da93c1487cb38ee51fcac47088cdd29854999/assessment.py#L187

Hello, when i read this code, its very nice and give me a great help.  And i have a question, in this line,  whats mean about @. 
Thanks!

**Comment by Jordy-VL** [comment]
If I am not mistaken, that indicates a dot product in numpy ;)
